name: CI
on:
  merge_group:
  pull_request:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
      - name: Run tests
        run: |
          npm install
          ./tests/run.sh
